FROM apache/airflow:latest-python3.9
RUN pip install --no-cache-dir airflow-provider-toloka
RUN pip install --no-cache-dir toloka-kit
RUN pip install --no-cache-dir crowd-kit
RUN pip install --no-cache-dir pandas
